version: "3.8"
services:
  movies:
    image: sumitjadhav652/train:latest
    ports:
      - 81:80
    deploy:
      replicas: 3

  train:
    image: sumitjadhav652/newmovies:latest
    ports:
      - 82:80
    deploy:
      replicas: 3

  dth:
    image: sumitjadhav652/dth:latest
    ports:
      - 83:80
    deploy:
      replicas: 3

  recharge:
    image: sumitjadhav652/recharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
